# Generated by Django 4.1 on 2023-02-12 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('happyf_dbquery', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matchid', models.CharField(max_length=200)),
                ('homeplayer', models.CharField(max_length=200)),
                ('guestplayer', models.CharField(max_length=200)),
                ('result', models.CharField(max_length=200)),
                ('home_conner_reslut', models.CharField(max_length=200)),
                ('home_attact', models.CharField(max_length=200)),
                ('home_dgattact', models.CharField(max_length=200)),
                ('guest_conner_reslut', models.CharField(max_length=200)),
                ('guest_attact', models.CharField(max_length=200)),
                ('guest_dgattact', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='RealTimeMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matchid', models.CharField(max_length=200)),
                ('compid', models.CharField(max_length=200)),
                ('realtimeresult', models.CharField(max_length=200)),
                ('home_odd', models.CharField(max_length=200)),
                ('guest_odd', models.CharField(max_length=200)),
                ('odd_term', models.CharField(max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='beforematch',
            name='date_time',
        ),
    ]
