# Generated by Django 4.1 on 2023-02-12 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('happyf_dbquery', '0002_matchresult_realtimematch_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='beforematch',
            name='date_time',
            field=models.DateTimeField(default='2021-01-01'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='matchresult',
            name='date_time',
            field=models.DateTimeField(default='2021-02-02'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='realtimematch',
            name='date_time',
            field=models.DateTimeField(default='2021-02-02'),
            preserve_default=False,
        ),
    ]
