# Generated by Django 4.1.7 on 2023-04-11 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('happyf_dbquery', '0003_beforematch_date_time_matchresult_date_time_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('t', models.DateTimeField(blank=True, null=True)),
                ('p', models.BigIntegerField(blank=True, null=True)),
                ('h', models.FloatField(blank=True, null=True)),
                ('a', models.FloatField(blank=True, null=True)),
                ('rt', models.TextField(blank=True, null=True)),
                ('hg', models.BigIntegerField(blank=True, null=True)),
                ('ag', models.BigIntegerField(blank=True, null=True)),
                ('st', models.BigIntegerField(blank=True, null=True)),
                ('matchid', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'testft',
                'managed': False,
            },
        ),
    ]
